version: '{build}'

image: Visual Studio 2017
configuration: Release

before_build:
- ps: nuget restore

build:
  verbosity: minimal

artifacts:
- path: YoutubeExplode\bin\$(configuration)\YoutubeExplode*.nupkg
  name: YoutubeExplode.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: 5VyEaGo5gRLr9HdkRFqS1enRq+K8Qarg1dzU33CE1dOmVXp43JaS2PQTNgsRHXkc
  artifact: YoutubeExplode.nupkg
  on:
    branch: master
    appveyor_repo_tag: true